from __future__ import annotations


class Transport:

    def send_sync(self, payload: str | bytes): ...

    async def send_async(self, payload: str | bytes): ...

    def recv_sync(self) -> str | bytes: ...

    async def recv_async(self) -> str | bytes: ...
